//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models.VehicleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerDetail
    {
        public long ioCode { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string OWNER_NAME { get; set; }
        public string ADDRESS { get; set; }
    }
}
