//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models.VehicleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public long icCode { get; set; }
        public string CUSTOMER_ID { get; set; }
        public Nullable<int> model { get; set; }
        public string make { get; set; }
        public string plateno { get; set; }
        public string fileno { get; set; }
        public string engineno { get; set; }
        public string chassisno { get; set; }
        public string color { get; set; }
        public string denom { get; set; }
        public Nullable<int> pd { get; set; }
        public Nullable<int> cylinder { get; set; }
        public string fuel { get; set; }
        public string series { get; set; }
        public string type { get; set; }
        public Nullable<int> grosswt { get; set; }
        public Nullable<int> netwt { get; set; }
        public Nullable<int> shipwt { get; set; }
        public Nullable<int> capwt { get; set; }
        public string vclass { get; set; }
        public System.DateTime trdate { get; set; }
        public string lto { get; set; }
        public string status { get; set; }
    }
}
