//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BRANCH
    {
        public string BRANCH_CODE { get; set; }
        public string BRANCH_NAME { get; set; }
        public string BRANCH_ADDRESS { get; set; }
        public string OFFICER_INCHARGE { get; set; }
        public string CONTACT_NO { get; set; }
        public string PAPIN_CODE { get; set; }
        public Nullable<decimal> LGT_RATE { get; set; }
        public string MUNICIPALITY { get; set; }
        public string ACTIVE { get; set; }
    }
}
