//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_COMPANY
    {
        public string COMP_ID { get; set; }
        public string NAME { get; set; }
        public string STADDR { get; set; }
        public string TELNO1 { get; set; }
        public string FAXNO { get; set; }
        public string EMAIL { get; set; }
        public string ZIP { get; set; }
        public string ACTIVE { get; set; }
        public string CONTACT_no { get; set; }
        public byte[] LOGO { get; set; }
        public string VAT { get; set; }
    }
}
