//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_EMPLOYEE
    {
        public string EMID { get; set; }
        public string DPID { get; set; }
        public string HOSPCD { get; set; }
        public string EMLNAME { get; set; }
        public string EMFNAME { get; set; }
        public string EMMNAME { get; set; }
        public string EMSEX { get; set; }
        public string USRID { get; set; }
        public Nullable<System.DateTime> EMDTHIRED { get; set; }
        public Nullable<System.DateTime> EMDTRESIGNED { get; set; }
        public string EMADDR { get; set; }
        public string EMTELNO1 { get; set; }
        public string EMSSSNO { get; set; }
        public string EMTINNO { get; set; }
        public string POSCDE { get; set; }
        public string LEVCDE { get; set; }
        public byte[] E_SIGN { get; set; }
    }
}
