//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PAIP
    {
        public long PAIP_ID { get; set; }
        public string PAPIN { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string PALNAME { get; set; }
        public string COMPANY_NAME { get; set; }
        public string BY_COMPNAME { get; set; }
        public string PAADDRESS { get; set; }
        public string MV_TYPE { get; set; }
        public string VEHICLE_CLASS { get; set; }
        public string PLATE_NO { get; set; }
        public string SERIAL_NO { get; set; }
        public string MOTOR_NO { get; set; }
        public string SEATING_CAPACITY { get; set; }
        public string MODEL_YR { get; set; }
        public string COVERAGE_YR { get; set; }
        public string MAKE { get; set; }
        public string SERIES { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string COLOR { get; set; }
        public string UN_WEIGHT { get; set; }
        public string ASSURED_TIN { get; set; }
        public Nullable<System.DateTime> INSURED_FROM { get; set; }
        public Nullable<System.DateTime> INSURED_TO { get; set; }
        public string REMARKS { get; set; }
        public string TAX_TYPE { get; set; }
        public string PLACE_ISSUED { get; set; }
        public string MV_FILENO { get; set; }
        public Nullable<System.DateTime> PAREGISTER { get; set; }
        public string COMP_ID { get; set; }
        public string BLT_FILENO { get; set; }
        public string BUS_PROF { get; set; }
        public Nullable<decimal> NO_DAYS { get; set; }
        public string PRO_RATA { get; set; }
        public Nullable<decimal> FLEET { get; set; }
        public string FUEL { get; set; }
        public string BRANCH { get; set; }
        public string NON_LTO { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string TYPE_BODY { get; set; }
        public string UPLOADED_CODE { get; set; }
        public Nullable<System.DateTime> UPLOADED_DATE { get; set; }
        public string RISK_CODE { get; set; }
        public string CONDUCTION_STICKER { get; set; }
    }
}
