//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PREMIUM_TYPE
    {
        public string CODE { get; set; }
        public string VEHICLE_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string COVERAGE_YR { get; set; }
        public string TYPE { get; set; }
        public string SERVICES { get; set; }
        public string INSURANCE_TYPE { get; set; }
    }
}
