//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_REGISTRATION_KEY
    {
        public string REGISTRATION_KEY { get; set; }
        public string SERIAL_KEY { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<System.DateTime> DATE_REGISTERED { get; set; }
        public string REGIONCODE { get; set; }
        public string PAPIN_CODE { get; set; }
    }
}
