//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_REGION
    {
        public string CODE { get; set; }
        public string REGION_NAME { get; set; }
        public string COC { get; set; }
        public string COI { get; set; }
        public string ACTIVE { get; set; }
        public string CODE_SERIES { get; set; }
        public string SATELLITE { get; set; }
        public string PAPIN_CODE { get; set; }
    }
}
