//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SHARING
    {
        public string COMPANY_CODE { get; set; }
        public Nullable<decimal> SHARING { get; set; }
        public Nullable<decimal> W_TAX { get; set; }
    }
}
