//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TPP
    {
        public long ID { get; set; }
        public string TPCD { get; set; }
        public string TPNAME { get; set; }
        public string TPTYPE { get; set; }
        public string ADDRESS { get; set; }
        public string TELNO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> BDAY { get; set; }
        public string TIN { get; set; }
        public string SPOUSE { get; set; }
        public string ADDRESS_SP { get; set; }
        public string TELNO_SP { get; set; }
        public string EMAIL_SP { get; set; }
        public string LN_AGENT { get; set; }
        public string INS_COMP { get; set; }
        public string TERMS { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public string MOBILE_NO { get; set; }
        public Nullable<decimal> COMMISSION { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public string LIC_NO { get; set; }
        public string UPLOADED_CODE { get; set; }
        public Nullable<System.DateTime> UPLOADED_DATE { get; set; }
    }
}
