//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TYPE_BODY
    {
        public string BODY_CODE { get; set; }
        public string BODY_DESC { get; set; }
        public string RISK_CODE { get; set; }
        public string VEHICLE_CLASS { get; set; }
    }
}
