//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_USER
    {
        public string USRID { get; set; }
        public string ROLCDE { get; set; }
        public string USRAPPPASS { get; set; }
        public string USRDBPASS { get; set; }
        public string USRDBID { get; set; }
        public string USRTYPE { get; set; }
        public string USRVIP { get; set; }
        public string USRLOCK { get; set; }
        public string SUPERUSER { get; set; }
        public string USRHEAD { get; set; }
        public string USRALL { get; set; }
        public string USRTAG { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
    }
}
