//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_OR
    {
        public long ID { get; set; }
        public decimal ORCUR { get; set; }
        public string HOSPCD { get; set; }
        public string ORSTART { get; set; }
        public string OREND { get; set; }
        public Nullable<System.DateTime> ORSDTE { get; set; }
        public string INIT { get; set; }
    }
}
