//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_PACK_PRICE
    {
        public string PKCD { get; set; }
        public string SVCD { get; set; }
        public Nullable<decimal> SUM_INSIRED { get; set; }
        public Nullable<decimal> BASIC_PREMIUM { get; set; }
        public Nullable<decimal> DOC_STAMP { get; set; }
        public Nullable<decimal> PREM_TAX { get; set; }
        public Nullable<decimal> LGT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> COMP_FEE { get; set; }
        public Nullable<decimal> CERT_FEE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> COMMISSION { get; set; }
        public string TYPE { get; set; }
    }
}
