//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_SGSI
    {
        public long ID { get; set; }
        public string SGNAME { get; set; }
        public Nullable<decimal> SGYR { get; set; }
        public Nullable<decimal> SGMO { get; set; }
        public Nullable<decimal> SGSERIES { get; set; }
        public string REGION { get; set; }
        public Nullable<decimal> START_SERIES { get; set; }
        public Nullable<decimal> END_SERIES { get; set; }
        public string PREFIX { get; set; }
    }
}
