//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RCTPLEntities : DbContext
    {
        public RCTPLEntities()
            : base("name=RCTPLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_PAIP> M_PAIP { get; set; }
        public virtual DbSet<T_BILLCHRGD> T_BILLCHRGD { get; set; }
        public virtual DbSet<T_BILLCHRGH> T_BILLCHRGH { get; set; }
        public virtual DbSet<T_COLLECTION> T_COLLECTION { get; set; }
        public virtual DbSet<T_SINO> T_SINO { get; set; }
        public virtual DbSet<T_TRACKING> T_TRACKING { get; set; }
        public virtual DbSet<TBL_SYSTEMUSERS> TBL_SYSTEMUSERS { get; set; }
        public virtual DbSet<TBL_VEHICLES> TBL_VEHICLES { get; set; }
        public virtual DbSet<TBL_WEBUSERS> TBL_WEBUSERS { get; set; }
    }
}
