//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BILLCHRGH
    {
        public long BILLH_ID { get; set; }
        public string BCHCHRGNO { get; set; }
        public string PAPIN { get; set; }
        public string TRKID { get; set; }
        public Nullable<System.DateTime> BCHDTE { get; set; }
        public string USRID { get; set; }
        public string PKCD { get; set; }
        public string UPLOADED_CODE { get; set; }
        public Nullable<System.DateTime> UPLOADED_DATE { get; set; }
    }
}
