//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BILLCHRGD
    {
        public long BILLD_ID { get; set; }
        public string BCHCHRGNO { get; set; }
        public int BCDSERIES { get; set; }
        public string BCDITMCD { get; set; }
        public string BCDESC { get; set; }
        public int BCDQTY { get; set; }
        public decimal BCDSP { get; set; }
        public Nullable<decimal> BCDPATCOVER { get; set; }
        public Nullable<decimal> BCDPATBAL { get; set; }
        public Nullable<decimal> BCDTPPCOVER { get; set; }
        public string DISCCD { get; set; }
        public string TPCD { get; set; }
        public string BCDTPPTAG { get; set; }
        public string COLORNUM { get; set; }
        public string BCDSINO { get; set; }
        public Nullable<decimal> BCDTPPBAL { get; set; }
        public Nullable<decimal> DOC_STAMP { get; set; }
        public Nullable<decimal> E_VAT { get; set; }
        public Nullable<decimal> LGT { get; set; }
        public Nullable<decimal> SUM_INSIRED { get; set; }
        public Nullable<decimal> COMP_FEE { get; set; }
        public Nullable<decimal> CERT_FEE { get; set; }
        public Nullable<decimal> BASIC_PREMIUM { get; set; }
        public string DOC_OR { get; set; }
        public string COI { get; set; }
        public Nullable<decimal> COMMISSION { get; set; }
        public string AUTHEN_CODE { get; set; }
        public Nullable<decimal> TAX_AMT { get; set; }
        public string WITH_COM { get; set; }
        public Nullable<decimal> W_TAX { get; set; }
        public Nullable<decimal> W_TAX_NET { get; set; }
        public Nullable<decimal> NO_DAYS { get; set; }
        public string PRO_RATA { get; set; }
        public string REG_TYPE { get; set; }
        public string TRANS_TYPE { get; set; }
        public string REGION { get; set; }
        public string ENDO_NO { get; set; }
        public string UPLOADED_CODE { get; set; }
        public Nullable<System.DateTime> UPLOADED_DATE { get; set; }
        public string LTFRB_DCODE { get; set; }
        public Nullable<System.DateTime> LTFRB_DDATE { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public Nullable<decimal> REFUND { get; set; }
        public Nullable<decimal> OTH_CHRGES { get; set; }
        public Nullable<decimal> TAXES { get; set; }
        public string CAN_POLICY { get; set; }
        public Nullable<System.DateTime> DATE_CANCEL { get; set; }
        public string can_user { get; set; }
        public string PRNT { get; set; }
        public Nullable<System.DateTime> DATE_PRINTED { get; set; }
        public string REF_NUM { get; set; }
        public Nullable<System.DateTime> DATEPAID { get; set; }
        public string VEHICLE_CODE { get; set; }
        public Nullable<decimal> COMP_SHARE { get; set; }
        public Nullable<decimal> TPP_SHARE { get; set; }
        public byte[] QR_IMAGE { get; set; }
        public Nullable<decimal> CTPL { get; set; }
        public Nullable<decimal> PL { get; set; }
        public Nullable<decimal> AUTHEN_FEE { get; set; }
        public string MUNICIPALITY { get; set; }
        public string COC_SERIES { get; set; }
        public Nullable<decimal> BAYAD_CENTER { get; set; }
        public string RISK_CODE { get; set; }
        public Nullable<decimal> LGT_RATE { get; set; }
        public Nullable<System.DateTime> INCEPTION_FROM { get; set; }
        public Nullable<System.DateTime> INCEPTION_TO { get; set; }
        public string CHARGES_OR { get; set; }
        public Nullable<decimal> W_TAX_SHARE { get; set; }
    }
}
