//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COLLECTION
    {
        public long COLL_ID { get; set; }
        public string COLNO { get; set; }
        public string USRID { get; set; }
        public System.DateTime COLORDTE { get; set; }
        public Nullable<decimal> COLAMT { get; set; }
        public string CLIENTCD { get; set; }
        public string COLPYMTYP { get; set; }
        public string COLPARTICULAR { get; set; }
        public string COLORNUM { get; set; }
        public string COLSTATOR { get; set; }
        public string COLREFNO { get; set; }
        public string BANK_NAME { get; set; }
        public string CARD_HOLDER { get; set; }
        public string CARD_NO { get; set; }
        public string COLREMARK { get; set; }
        public string COLPAYOR { get; set; }
        public string WITH_TAX { get; set; }
        public Nullable<decimal> TAX_AMT { get; set; }
        public string UPLOADED_CODE { get; set; }
        public Nullable<System.DateTime> UPLOADED_DATE { get; set; }
        public string DCR_NO { get; set; }
        public string DEPOSITED { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string CHECK_NO { get; set; }
        public string BRANCH_NAME { get; set; }
    }
}
