//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ENDORSEMENT
    {
        public long ENDO_ID { get; set; }
        public string PAPIN { get; set; }
        public string ENDO_NO { get; set; }
        public Nullable<System.DateTime> DATE_ENDO { get; set; }
        public string PLATE_NO { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string CHASSIS { get; set; }
        public string MOTOR { get; set; }
        public string COLOR { get; set; }
        public string LTFRB { get; set; }
        public string ROUTE_FROM { get; set; }
        public string ROUTE_TO { get; set; }
        public string BY_COMP { get; set; }
        public string MV_FILENO { get; set; }
        public string MODEL { get; set; }
        public Nullable<System.DateTime> INSURED_START { get; set; }
        public Nullable<System.DateTime> INSURED_END { get; set; }
        public string SERVICE { get; set; }
        public string BODY { get; set; }
        public string MAKE { get; set; }
        public string POLICY_NO { get; set; }
        public string COMMENTS { get; set; }
        public string POL_TYPE { get; set; }
        public string UPLOADED_CODE { get; set; }
        public Nullable<System.DateTime> UPLOADED_DATE { get; set; }
        public string POLICY_COI { get; set; }
        public Nullable<System.DateTime> DATE_FROM_PPAI { get; set; }
        public Nullable<System.DateTime> DATE_TO_PPAI { get; set; }
        public string NAME_H { get; set; }
        public string ADDRESS_H { get; set; }
    }
}
