//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TRACKING
    {
        public long TRACKING_ID { get; set; }
        public string TRKID { get; set; }
        public string PAPIN { get; set; }
        public Nullable<System.DateTime> TRKDTEADMT { get; set; }
        public string PCID { get; set; }
        public string TPCD { get; set; }
        public string TRKREMARK { get; set; }
        public string TRKRECENT { get; set; }
        public string TRKCAT { get; set; }
        public string TRKUSRID { get; set; }
        public string UPLOADED_CODE { get; set; }
        public Nullable<System.DateTime> UPLOADED_DATE { get; set; }
    }
}
