//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAYMENTS
    {
        public long PAYMENT_ID { get; set; }
        public string USERNAME { get; set; }
        public string C_NAME { get; set; }
        public string PLATE { get; set; }
        public string CHASIS { get; set; }
        public string ENGINE { get; set; }
        public string VEHICLE { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
    }
}
