//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VEHICLES
    {
        public string PKCD { get; set; }
        public string PACKAGE_DESC { get; set; }
        public string SERVICE_CODE { get; set; }
        public string SERVICE_TYPE { get; set; }
        public Nullable<decimal> SUM_INSURED { get; set; }
        public Nullable<decimal> BASIC_PREMIUM { get; set; }
        public Nullable<decimal> DOC_STAMP { get; set; }
        public Nullable<decimal> LGT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> COMP_FEE { get; set; }
        public Nullable<decimal> CERT_FEE { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public string VEHICLE_CODE { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public long VEHICLE_ID { get; set; }
    }
}
