//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SYSTEMUSERS
    {
        public long ADMIN_ID { get; set; }
        public string USER_CODE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string E_PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string NAME { get; set; }
        public string CONTACT_NUMBER { get; set; }
        public string MAILING_ADDRESS { get; set; }
        public Nullable<System.DateTime> DATE_REGISTERED { get; set; }
        public string REGISTERED_BY { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string USER_TYPE { get; set; }
    }
}
