//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTPL_WebProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSEARCH
    {
        public long SEARCH_ID { get; set; }
        public string PLATE_NO { get; set; }
        public Nullable<int> MODEL { get; set; }
        public string MAKE { get; set; }
        public string MVFILE_NO { get; set; }
        public string ENGINE { get; set; }
        public string CHASIS_NO { get; set; }
        public string COLOR { get; set; }
        public string TYPE_SERVICE { get; set; }
        public string SERIES { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PAPIN { get; set; }
    }
}
